### PR TITLE
Adding body copy

### PR DESCRIPTION
**Pull request by nicoleslaw**
Plz review in case it needs a class

### CODE REVIEW

**Comment by noahmanger** [comment]
Hmm this just looks a little weird to me. What about putting it under "Common concerns"?

image

**Comment by nicoleslaw** [comment]
Sounds good. We can also cut the `Common concerns` subhead if it's better that way. I couldn't decide.

**Comment by noahmanger** [comment]
Paging @ericronne for your 👀

**Comment by ericronne** [comment]
Sorry I'm out for the rest of the week. I may well have neglected to
mention, sorry! 😱

Will try to take a look

Sent from my iPhone

On Aug 10, 2017, at 1:28 PM, Noah Manger <notifications@github.com> wrote:

Paging @ericronne <https://github.com/ericronne> for your 👀

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/18F/worker-dol-gov/pull/35#issuecomment-321619599>, or mute
the thread

**Comment by ericronne** [comment]
My quick reco would be to only use the vertical rules in sidebars, and to make the bullets red. Something like this.

image

Intro paragraphs should all probably be bumped up a notch, but can possibly deal with later. thx!

**Comment by noahmanger** [comment]
Totally forgot about this. Thanks!

image

**Comment by noahmanger** [comment]
Replaced with a push to master.

**Comment by ericronne** [comment]
@noahmanger greased ⚡️ !

**Pull request closed without merging**
